(()=>{const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],fmt=n=>new Intl.NumberFormat('ar-SA').format(n)+' ر.س';let mode='buy',purpose='بيع',current=1,favs=[1];const titles={home:'الرئيسية',search:'البحث',detail:'تفاصيل العقار',add:'أضف عقارك',request:'اطلب عقارك',favorites:'المفضلة',notifications:'الإشعارات',account:'حسابي'};
function go(id){all('.page').forEach(x=>x.classList.toggle('active',x.id===id));$('#title').textContent=titles[id]||'دار';all('nav [data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='favorites')drawFavs();if(id==='account')$('#favNum').textContent=favs.length;scrollTo(0,0)}
function card(x){return `<article class="card"><div class="thumb"></div><div class="ci"><b>${fmt(x.price)}</b><span>${x.title}</span><small>⌖ ${x.city} · ${x.district}</small><button data-open="${x.id}">التفاصيل</button></div></article>`}
function drawHome(){$('#cards').innerHTML=PROPERTIES.filter(x=>x.type==='buy').map(card).join('')}
function drawSearch(){const q=$('#q').value.trim(),city=$('#city').value,kind=$('#kind').value;const rows=PROPERTIES.filter(x=>x.type===mode&&(!q||(x.title+x.city+x.district+x.kind).includes(q))&&(!city||x.city===city)&&(!kind||x.kind===kind));$('#count').textContent=rows.length+' عقار';$('#results').innerHTML=rows.map(x=>`<article class="result"><div class="thumb"></div><div><b>${x.title}</b><small>⌖ ${x.city} · ${x.district}</small><strong>${fmt(x.price)}</strong><button data-open="${x.id}">التفاصيل</button></div></article>`).join('')||'<p class="muted">لا توجد نتائج مطابقة.</p>'}
function openProp(id){const x=PROPERTIES.find(v=>v.id===id);if(!x)return;current=id;$('#badge').textContent=x.label;$('#dTitle').textContent=x.title;$('#dPlace').textContent='⌖ '+x.city+' · '+x.district;$('#dPrice').textContent=fmt(x.price);$('#facts').innerHTML=`<div><b>${x.beds}</b><small>غرف</small></div><div><b>${x.baths}</b><small>حمامات</small></div><div><b>${x.area} م²</b><small>المساحة</small></div>`;$('#desc').textContent=x.description;$('#features').innerHTML=x.features.map(v=>`<span>✓ ${v}</span>`).join('');syncFav();go('detail')}
function syncFav(){$('#favBtn').textContent=favs.includes(current)?'♥ محفوظ في المفضلة':'♡ حفظ في المفضلة'}
function drawFavs(){const rows=PROPERTIES.filter(x=>favs.includes(x.id));$('#favList').innerHTML=rows.length?rows.map(x=>`<article class="result"><div class="thumb"></div><div><b>${x.title}</b><small>⌖ ${x.city} · ${x.district}</small><strong>${fmt(x.price)}</strong><button data-open="${x.id}">التفاصيل</button></div></article>`).join(''):'<p class="muted">لا توجد عقارات محفوظة.</p>'}
document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g){if(g.dataset.go==='search'&&$('#homeQ').value){$('#q').value=$('#homeQ').value;drawSearch()}go(g.dataset.go);return}const o=e.target.closest('[data-open]');if(o){openProp(Number(o.dataset.open));return}if(e.target.dataset.mode){mode=e.target.dataset.mode;all('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));drawSearch()}if(e.target.dataset.purpose){purpose=e.target.dataset.purpose;all('[data-purpose]').forEach(b=>b.classList.toggle('active',b.dataset.purpose===purpose))}});
['#q','#city','#kind'].forEach(s=>$(s).addEventListener(s==='#q'?'input':'change',drawSearch));
$('#favBtn').addEventListener('click',()=>{favs=favs.includes(current)?favs.filter(x=>x!==current):[...favs,current];syncFav()});
$('#preview').addEventListener('click',()=>{$('#aMsg').textContent=!$('#aCity').value||!$('#aPrice').value?'أدخل المدينة والسعر أولًا.':`✓ إعلان ${purpose} ${$('#aKind').value} جاهز للمعاينة — لم يتم نشره.`});
$('#makeReq').addEventListener('click',()=>{const city=$('#rCity').value,budget=Number($('#budget').value),kind=$('#rKind').value;if(!city||!budget){$('#rResult').innerHTML='<p class="gold">اختر المدينة وأدخل الميزانية.</p>';return}const m=PROPERTIES.filter(x=>x.kind===kind&&x.city===city&&x.price<=budget);$('#rResult').innerHTML=`<div class="match"><b>تم إنشاء الطلب ✓</b><span>${kind} · ${city} · حتى ${fmt(budget)}</span><strong>${m.length?`وجدنا ${m.length} مطابقة تجريبية`:'لا توجد مطابقة كاملة حاليًا'}</strong></div>`});
drawHome();drawSearch()})();